{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    {{- include "kubernetes.io/tls-acme" . | indent 4}} 
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*" 
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET,PUT,POST,DELETE,PATCH,OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"   
    nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/session-cookie-name: "activiti-cloud-notifications-graphql-route"
    nginx.ingress.kubernetes.io/session-cookie-hash: "md5"
    nginx.ingress.kubernetes.io/session-cookie-path: "/"
    {{- range $key, $value := .Values.global.gateway.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ include "ingresshost" $ | quote }}
      http:
        paths:
        {{- if .Values.ingress.web.enabled }}
        - path: {{ tpl .Values.ingress.path . }}{{ .Values.ingress.web.path }}
          backend:
            serviceName: {{ template "servicename" . }}
            servicePort: {{ .Values.service.externalPort }}
        {{- end }}
        {{- if .Values.ingress.ws.enabled }}
        - path: {{ tpl .Values.ingress.path . }}{{ .Values.ingress.ws.path }}
          backend:
            serviceName: {{ template "servicename" . }}
            servicePort: {{ .Values.service.externalPort }}
        {{- end }}
        {{- if .Values.ingress.graphiql.enabled }}
        - path: {{ tpl .Values.ingress.path . }}{{ .Values.ingress.graphiql.path }}
          backend:
            serviceName: {{ template "servicename" . }}
            servicePort: {{ .Values.service.externalPort }}
        {{- end }}
  {{- if default .Values.global.config.tls .Values.ingress.tls}}
  tls:
  - secretName: {{ template "tlssecretname" . }}
    hosts:
    - {{ include "ingresshost" $ }}
  {{- end }}
{{- end }}